### PR TITLE
Align CMake recipe with 'modern' CMake

### PR DESCRIPTION
**Pull request by samangh**
This merge requests makes some modifications to the CMake recipe to align it to 'modern' CMake (see https://cliutils.gitlab.io/modern-cmake/).

The changes are specifically:

- 0b397c3: this allows others to include your project by simply adding your project via `add_subdirectory (wampcc)`
- 9be2056: add component names to the targets so that one can selectively install the headers/libraries, and build DEB/RPM packages;
- 5967a0c: this allows for automatic detection of the headers and appropriate library dependencies for others who may wish to include your library as part of a larger CMake project.
- a14af7b: Build Debian packages using CPack

### CODE REVIEW

**Comment by darrenjs** [comment]
Hi.  Have you tested the changes on Windows / Linux , or both?  And it is still compatible with earlier cmakes?

**Comment by samangh** [comment]
I have tested the changes on Linux, but not macOS or Windows. I'll try to do some testing next week and will get back to you.

This will be compatible with CMake 3.8.1 (released 2017) and above. It may be compatible with earlier CMakes, but I haven't tested it. Again, I'll try to do some testing with earlier versions and will get back to you.

**Comment by darrenjs** [comment]
Ok, thanks for info.  I will do a test for windows; generally I think if it works on windows & Linux, then MacOS should work.  Fyi wampcc does build on mac.

**Comment by darrenjs** [comment]
Hi,  I have tried building on centos 7.   Doesn't seem to work.   It doesn't find the  jansson.h header; fails very early in the compile sequence.     I am invoking cmake using -DJANSSON_DIR to provide a custom location to my jansson library.

**Comment by samangh** [comment]
I tested it on Debian/Ubuntu and it seemed to work, I'll install CentOS on a virtual machine to see if there is any difference.

It's a bit complicated on my end, because I'm using a modified version of wampcc at work, and have to 'cherrypick' the relevant commits from the private work repo to Github, so may be I missed a commit. I'll have a look.

Appreciate your testing and patience. It might take me 1-2 weeks to get around to fixing this!

**Comment by darrenjs** [comment]
... but, for your testing, do you use the -DJANSSON_DIR  options etc (and same for libuv), or, do you just  default to finding the system installed versions?  I wonder if that is difference of why works for you, and not on my machine?

**Comment by samangh** [comment]
Sorry for the delay in getting back to you. The problem was because of misspelling 'Jansson' instead of 'jansson'. I've fixed this in the latest commit.

I have now tested this with both system installed version and custom (via `-DJANSSON_DIR`) version of Jansson. 

Did you get a chance to test this on Windows?

**Comment by samangh** [comment]
I have now checked this on Windows. With the latest commit this also compiles fine on Windows. I'm using Windows 10 with Visual Studio 2017.

The last commit also closes issue #14 as it allows a custom OpenSSL location to be defined using `-DOPENSSL_ROOT_DIR`

**Comment by darrenjs** [comment]
Confirm I also get build now working on Linux, using same set of commands as I attempted previously :-)  ... I'll check Windows soon

**Comment by darrenjs** [comment]
Windows build works :-)

**Pull request merged**
