### PR TITLE
use find_package instead of pkgconfig in cmake

### PR DESCRIPTION
**Pull request by Mdrbhatti**
Building wampcc on Windows and MSVC requires some extra steps. This PR intends to remove those obstacles so you can easily build wampcc after running cmake without any other configuration. Also provides some additional output during the building process.

1. OpenSSL include paths were not being set for MSVC.
2. Pkgconfig is very painful to setup on windows (i couldn't get it working), and find_package directive is a much better alternative than manually setting the library paths (also officially recommended by cmake). #30 

I have tested this PR on both Windows 7 and Linux (Ubuntu 16.04.4).

### CODE REVIEW

**Comment by Mdrbhatti** [comment]
The cmake documentation for ``find_package`` recommends setting the `PACKAGENAME_ROOT` environment variable. Currently, wampcc is using cmake commandline arguments for `JANSSON_DIR` and `LIBUV_DIR`. Do you think it would be better to switch over to an environment variable approach? E.g. Using `$ENV{JANSSON_ROOT}` in `FindJansson.cmake` file etc.

https://cmake.org/cmake/help/latest/command/find_package.html

**Comment by darrenjs** [comment]
Hi ... does this approach still allow the location of libuv & jansson to be provided on the command line?

**Comment by darrenjs** [comment]
Hi,

I tried using your repo, but I get a link error, during creation of libwampcc_json.so

I launched cmake as:
```shell
cmake \
-DCMAKE_BUILD_TYPE=Debug \
-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
-DLIBUV_DIR=${HOME}/opt/libuv-1.10.2 \
-DJANSSON_DIR=${HOME}/opt/jansson-2.10 \
-DCMAKE_INSTALL_PREFIX=/var/tmp/wampcc_Mdrbhatti \
../wampcc
```

... and fails quickly ...

```shell
[  5%] Linking CXX shared library libwampcc_json.so
cd /var/tmp/wampcc/Mdrbhatti/build/libs/json && /usr/bin/cmake -E cmake_link_script CMakeFiles/wampcc_json_shared.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC  -Wall -g  -shared -Wl,-soname,libwampcc_json.so.6 -o libwampcc_json.so.6.0.0 CMakeFiles/wampcc_json_shared.dir/json.cc.o CMakeFiles/wampcc_json_shared.dir/json_pointer.cc.o CMakeFiles/wampcc_json_shared.dir/msgpack_serialiser.cc.o CMakeFiles/wampcc_json_shared.dir/vendors.cc.o -ljansson
/usr/bin/x86_64-linux-gnu-ld: cannot find -ljansson
```

I notice that this link line doesn't contain the library path to libjansson (whereas on the current wampcc master branch it does have the link library, which comes about via the `link_directories` statement in the top-level CMakeLists.txt).

FYI here is the output from the end of the cmake phase, showing the variables you added:

```
-- OpenSSL_INCLUDE_DIR:      /usr/include
-- OpenSSL_LIBRARIES:        /usr/lib/x86_64-linux-gnu/libssl.so/usr/lib/x86_64-linux-gnu/libcrypto.so
-- LIBUV_INCLUDE_DIRS:       /home/darrens/opt/libuv-1.10.2/include
-- LIBUV_LIBRARIES:          /home/darrens/opt/libuv-1.10.2/lib/libuv.so
-- JANSSON_INCLUDE_DIR:      /home/darrens/opt/jansson-2.10/include
-- JANSSON_LIBRARY:          /home/darrens/opt/jansson-2.10/lib/libjansson.so
-- JANSSON_VERSION:          2.10
```

Would be nice to understand why its not working for me, since I like your approach of moving the janson deps to separate makefike.

**Comment by Mdrbhatti** [comment]
Ah, I just realized I only tested building the static libs. Does it work for you now?

**Comment by darrenjs** [comment]
Hi, this seems better, thanks.  I haven't attempted my windows build yet.

**Comment by darrenjs** [comment]
Hi, I've attempted VSC++ build, but getting a failure.   I think the problem is that wampcc headers are being found via system or install-directory, rather than from the source directory   (and this is a problem because the headers I have lying around in the installation directory are from an earlier build).

I can see this from the VSC++ include options that get displayed during the build.  Here is  what gets included for the current master version:

```
CL.exe /c /IE:\wampcc\wampcc_BUILD /IE:\wampcc\wampcc\include /IE:\wampcc\wampcc\3rdparty\websocketpp /IE:\wampcc\wampcc\3rdparty /IC:\dev\libs\include
```
And here is the version from your repo:
```
CL.exe /c /IC:\dev\libs\include /IE:\wampcc\wampcc_BUILD /IE:\wampcc\wampcc\include /IE:\wampcc\wampcc\3rdparty\websocketpp /IE:\wampcc\wampcc\3rdparty
```

We can see, in the latter, the system directory is first, and so wampcc headers will be pulled from there (if any old ones are lying around).  I think we need to somehow get the system include directory to be at the end of the list (like in the original).

**Comment by darrenjs** [comment]
I think problem is line 64 in the root CMakeLists.txt.   That places the system include in front of the wamp includes.  I placed this instead at line 129, and the build (on VSC++) worked.

**Comment by Mdrbhatti** [comment]
Hi, so with your change, is it now working on both linux and windows? Could you push your changes to this pull request?

**Comment by Mdrbhatti** [comment]
Still works for me. Thanks!

**Pull request merged**
