### PR TITLE
Added option to use external ssl context configuration

### PR DESCRIPTION
**Pull request by hannu-h**
Pullrequest is related to https://github.com/darrenjs/wampcc/issues/25 
After some consideration for different approach, I fould this, completeley externalised ssl context creation to be the easiest from library maintenance point of view. No assumptions or complex logic about the context needed.

### CODE REVIEW

**Comment by darrenjs** [comment]
Hi,

Yeah, this seems like a reasonable approach; allow the user to provide a factory that creates a custom ssl context.   Regarding the current proposal though, two thoughts:  the naming convention diverges from the lower-case/underscore convention used through-out the existing wampcc code, and its preferable to avoid differences.  Second, on modern c++, the factory pattern can more easily be implemented using a std::function<> , e.g.,

```c++
std::function < SSL_CTX* (const struct ssl_config &) > custom_ssl_context_factory; // default is nullptr;

if (custom_ssl_context_factory) { m_ctx = custom_ssl_context_factory(m_config); } // etc
```
.... advantage of this is that the additional ssl_customCtxCreator class and header are no longer required.

**Comment by hannu-h** [comment]
PR updated as suggested

**Comment by darrenjs** [comment]
thanks for changes ... one alternation I will make later is to try and move the openssl include out from the public header.  I will use a forward instead.  useful to do this, so that less headers make it in to user code.

**Comment by darrenjs** [comment]
I pushed an update.  The include of openssl.h has been removed form the wampcc public header.  This is beneficial to do, since it means that wampcc can still be used even if the openssl headers are not available.  So instead of returning SSL_CTX, the creator function now returns a void*.  This makes the API a little more tricky to use, however,  use of a custom SSL_CTX is already in the domain of advanced behaviour, so I think it fine.

**Pull request merged**
